version: '3.8'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drawtrack-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    restart: unless-stopped
    networks:
      - drawtrack-network

networks:
  drawtrack-network:
    driver: bridge
